### ISSUE TITLE
verify that data is cleared on exit

### ISSUE THREAD

**Issue by samoftheanna** [samoftheanna/email-pdf#10]
there is a clear cache method available. just need to make sure it is called when the exit button is clicked.

**Comment by samoftheanna** [comment]
@tsl8r new issue from jim

**Comment by samoftheanna** [comment]
i'm assuming we want `removeAll()` from here: https://docs.angularjs.org/api/ng/service/$cacheFactory

**Comment by samoftheanna** [comment]
i'm getting nowhere with this.

**Comment by tylerslater-io** [comment]
almost done with it
