### ISSUE TITLE
names not reversed in pdf for cjk languages

### ISSUE THREAD

**Issue by samoftheanna** [samoftheanna/email-pdf#3]

**Comment by samoftheanna** [comment]
@tsl8r can you work on this?

**Comment by tylerslater-io** [comment]
@samoftheanna Yup, I'll assign it to myself. Do you want to commit your code and merge? Or do you want me to merge all the branches together?

**Comment by samoftheanna** [comment]
so sorry. i had to run to my mom's. i'll go ahead and merge now

**Comment by tylerslater-io** [comment]
No worries, I had to drive home anyway

**Comment by samoftheanna** [comment]
@tsl8r between this and clearing the cache on exit, where would i be most useful?
